# ============================================
# AWS Secrets Manager — Secure Credential Storage
# ============================================
# This file creates ALL secrets used across the entire project.
# 
# Secrets 1-3: Created in Week 3 (Production)
# Secrets 4-5: Created in Week 3 (DevOps — used by Week 9)
# 
# The actual values for Secrets 4-5 must be set manually after apply.
# Terraform creates the secret containers, but you populate the values.

# ============================================
# SECRET 1 — RDS Master Password
# ============================================
# Used by: Payment-api pod at startup (Stage 6C)
# Used by: Week 5 RDS Aurora cluster
# Password: 32 chars, special characters allowed

resource "aws_secretsmanager_secret" "rds_master" {
  name        = "absa/rds/master-password"
  description = local.secrets.rds_master_password.description
  kms_key_id  = aws_kms_key.secrets.key_id
  recovery_window_in_days = 7

  tags = merge(local.common_tags, {
    Name = "ABSA-RDS-Master-Password"
  })
}

resource "random_password" "rds_master" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
  min_special      = 4
  min_upper        = 4
  min_lower        = 4
  min_numeric      = 4
}

resource "aws_secretsmanager_secret_version" "rds_master" {
  secret_id     = aws_secretsmanager_secret.rds_master.id
  secret_string = jsonencode({
    username = "absa_admin"
    password = random_password.rds_master.result
    engine   = "aurora-postgresql"
    host     = "absa-rds-cluster.cluster-abcdefg.eu-west-1.rds.amazonaws.com"
    port     = "5432"
  })
}

# ============================================
# SECRET 2 — API Gateway Client Credentials
# ============================================
# Used by: Payment-api pod at startup (Stage 6A)
# Used by: Week 5 API Gateway client validation
# Password: 32 chars, special characters allowed

resource "aws_secretsmanager_secret" "api_gateway" {
  name        = "absa/api-gateway/client-secret"
  description = local.secrets.api_gateway_key.description
  kms_key_id  = aws_kms_key.secrets.key_id
  recovery_window_in_days = 7

  tags = merge(local.common_tags, {
    Name = "ABSA-API-Gateway-Client-Secret"
  })
}

resource "random_password" "api_gateway" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
  min_special      = 4
  min_upper        = 4
  min_lower        = 4
  min_numeric      = 4
}

resource "aws_secretsmanager_secret_version" "api_gateway" {
  secret_id     = aws_secretsmanager_secret.api_gateway.id
  secret_string = jsonencode({
    client_id     = "absa-mobile-app"
    client_secret = random_password.api_gateway.result 
    environment   = "production"
  })
}

# ============================================
# SECRET 3 — Redis Auth Token
# ============================================
# Used by: Payment-api pod at startup (Stage 6B)
# Used by: Week 5 ElastiCache Redis
# Password: 32 chars, special characters allowed

resource "aws_secretsmanager_secret" "redis_auth" {
  name        = "absa/elasticache/redis-auth-token"
  description = local.secrets.redis_auth_token.description
  kms_key_id  = aws_kms_key.secrets.key_id
  recovery_window_in_days = 7

  tags = merge(local.common_tags, {
    Name = "ABSA-Redis-Auth-Token"
  })
}

resource "random_password" "redis_auth" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
  min_special      = 4
  min_upper        = 4
  min_lower        = 4
  min_numeric      = 4
}

resource "aws_secretsmanager_secret_version" "redis_auth" {
  secret_id     = aws_secretsmanager_secret.redis_auth.id
  secret_string = jsonencode({
    auth_token  = random_password.redis_auth.result
    redis_host  = "absa-redis-cluster.abcdefg.cache.amazonaws.com"
    redis_port  = "6379"
  })
}

# ============================================
# SECRET 4 — Docker Hub Credentials (Week 9)
# ============================================
# Used by: ECR pull-through cache for Docker Hub
# Used by: Week 9 CodeBuild to authenticate to Docker Hub
# 
# IMPORTANT: This secret is NOT populated by Terraform.
# You must set the value manually after apply:
# 
# aws secretsmanager put-secret-value \
#   --secret-id absa/devops/docker-hub-credentials \
#   --secret-string '{"username":"your-dockerhub-username","accessToken":"your-access-token"}'
# 
# Why not populate in Terraform?
#   - Docker Hub credentials are generated by Docker Hub, not by Terraform
#   - The access token must be created in Docker Hub's interface
#   - Never store credentials in Terraform code
#   - Manual population is the secure approach

resource "aws_secretsmanager_secret" "docker_hub_credentials" {
  name        = "absa/devops/docker-hub-credentials"
  description = "Docker Hub credentials for ECR pull-through cache"
  kms_key_id  = aws_kms_key.secrets.key_id
  recovery_window_in_days = 30

  tags = merge(local.common_tags, {
    Name = "ABSA-Docker-Hub-Credentials"
    Purpose = "DevOps"
  })
}

# NOTE: No random_password for Docker Hub credentials.
# The token must be generated manually in Docker Hub.

# NOTE: No secret_version for Docker Hub credentials.
# The value must be set manually using AWS CLI:
# 
# aws secretsmanager put-secret-value \
#   --secret-id absa/devops/docker-hub-credentials \
#   --secret-string '{"username":"your-dockerhub-username","accessToken":"your-access-token"}'

# ============================================
# SECRET 5 — Infracost API Key (Week 9)
# ============================================
# Used by: buildspec_terraform.yml for cost estimation
# Used by: Week 9 Terraform validation pipeline
# 
# IMPORTANT: This secret is NOT populated by Terraform.
# You must set the value manually after apply:
# 
# aws secretsmanager put-secret-value \
#   --secret-id absa/devops/infracost-api-key \
#   --secret-string '{"api_key":"your-infracost-api-key"}'
# 
# Infracost API key is generated by Infracost (not by AWS/Terraform)
# Sign up at: https://www.infracost.io/

resource "aws_secretsmanager_secret" "infracost_api_key" {
  name        = "absa/devops/infracost-api-key"
  description = "Infracost API key for Terraform cost estimation"
  kms_key_id  = aws_kms_key.secrets.key_id
  recovery_window_in_days = 30

  tags = merge(local.common_tags, {
    Name = "ABSA-Infracost-API-Key"
    Purpose = "DevOps"
  })
}

# NOTE: No random_password for Infracost API key.
# The API key must be generated manually in Infracost.

# NOTE: No secret_version for Infracost API key.
# The value must be set manually using AWS CLI:
# 
# aws secretsmanager put-secret-value \
#   --secret-id absa/devops/infracost-api-key \
#   --secret-string '{"api_key":"your-infracost-api-key"}'